# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vahe1525/Documents/Git/RotatingPicture

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vahe1525/Documents/Git/RotatingPicture

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vahe1525/Documents/Git/RotatingPicture/CMakeFiles /home/vahe1525/Documents/Git/RotatingPicture//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vahe1525/Documents/Git/RotatingPicture/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RotateImage

# Build rule for target.
RotateImage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RotateImage
.PHONY : RotateImage

# fast build rule for target.
RotateImage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/build
.PHONY : RotateImage/fast

Main.o: Main.cpp.o
.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i
.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s
.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Main.cpp.s
.PHONY : Main.cpp.s

Pixel.o: Pixel.cpp.o
.PHONY : Pixel.o

# target to build an object file
Pixel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Pixel.cpp.o
.PHONY : Pixel.cpp.o

Pixel.i: Pixel.cpp.i
.PHONY : Pixel.i

# target to preprocess a source file
Pixel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Pixel.cpp.i
.PHONY : Pixel.cpp.i

Pixel.s: Pixel.cpp.s
.PHONY : Pixel.s

# target to generate assembly for a file
Pixel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Pixel.cpp.s
.PHONY : Pixel.cpp.s

Point.o: Point.cpp.o
.PHONY : Point.o

# target to build an object file
Point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Point.cpp.o
.PHONY : Point.cpp.o

Point.i: Point.cpp.i
.PHONY : Point.i

# target to preprocess a source file
Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Point.cpp.i
.PHONY : Point.cpp.i

Point.s: Point.cpp.s
.PHONY : Point.s

# target to generate assembly for a file
Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Point.cpp.s
.PHONY : Point.cpp.s

Webcam.o: Webcam.cpp.o
.PHONY : Webcam.o

# target to build an object file
Webcam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Webcam.cpp.o
.PHONY : Webcam.cpp.o

Webcam.i: Webcam.cpp.i
.PHONY : Webcam.i

# target to preprocess a source file
Webcam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Webcam.cpp.i
.PHONY : Webcam.cpp.i

Webcam.s: Webcam.cpp.s
.PHONY : Webcam.s

# target to generate assembly for a file
Webcam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RotateImage.dir/build.make CMakeFiles/RotateImage.dir/Webcam.cpp.s
.PHONY : Webcam.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RotateImage"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... Pixel.o"
	@echo "... Pixel.i"
	@echo "... Pixel.s"
	@echo "... Point.o"
	@echo "... Point.i"
	@echo "... Point.s"
	@echo "... Webcam.o"
	@echo "... Webcam.i"
	@echo "... Webcam.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

